/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 city2.gltf --types --transform --shadows 
Files: city2.gltf [965.55KB] > /Users/Carsten.Hoyer/Workspace/glyptoteket/public/city2-transformed.glb [391.68KB] (59%)
*/
// @ts-nocheck
import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Circle001-brown-0"]: THREE.Mesh;
    ["light-light-0"]: THREE.Mesh;
    bus_station_ark_brown_0: THREE.Mesh;
    bus_station_Material001_0: THREE.Mesh;
    bus_station_nokhody_0: THREE.Mesh;
    bus_station_yellow_0: THREE.Mesh;
    chaire_black_0: THREE.Mesh;
    chaire_chaire_0: THREE.Mesh;
    Cube024_ark_brown_0: THREE.Mesh;
    Cube024_gree_0: THREE.Mesh;
    Cube029_keremi_0: THREE.Mesh;
    Cube029_Material001_0: THREE.Mesh;
    Cube029_Material002_0: THREE.Mesh;
    Cube029_red_0: THREE.Mesh;
    Cube031_ark_brown_0: THREE.Mesh;
    Cube031_cheragh_0: THREE.Mesh;
    Cube128_ark_brown_0: THREE.Mesh;
    Cube128_gree_0: THREE.Mesh;
    Cube145_gree_0: THREE.Mesh;
    Cube177_gree_0: THREE.Mesh;
    Cube224_gree_0: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshPhongMaterial;
    PaletteMaterial003: THREE.MeshPhongMaterial;
    PaletteMaterial002: THREE.MeshPhongMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/city2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Circle001-brown-0"].geometry}
        material={materials.PaletteMaterial001}
        position={[-40.046, 11.3, 102.283]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.076}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["light-light-0"].geometry}
        material={materials.PaletteMaterial003}
        position={[-48.309, 6.942, 131.344]}
        scale={0.003}
      />
      <instancedMesh
        args={[
          nodes.bus_station_ark_brown_0.geometry,
          materials.PaletteMaterial001,
          6,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.bus_station_ark_brown_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.bus_station_Material001_0.geometry,
          materials.PaletteMaterial001,
          6,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.bus_station_Material001_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.bus_station_nokhody_0.geometry,
          materials.PaletteMaterial001,
          6,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.bus_station_nokhody_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.bus_station_yellow_0.geometry,
          materials.PaletteMaterial001,
          6,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.bus_station_yellow_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.chaire_black_0.geometry, materials.PaletteMaterial001, 27]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.chaire_black_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.chaire_chaire_0.geometry,
          materials.PaletteMaterial001,
          27,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.chaire_chaire_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube024_ark_brown_0.geometry,
          materials.PaletteMaterial001,
          50,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube024_ark_brown_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube024_gree_0.geometry, materials.PaletteMaterial001, 34]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube024_gree_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube029_keremi_0.geometry,
          materials.PaletteMaterial001,
          9,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube029_keremi_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube029_Material001_0.geometry,
          materials.PaletteMaterial001,
          9,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube029_Material001_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube029_Material002_0.geometry,
          materials.PaletteMaterial001,
          9,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube029_Material002_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube029_red_0.geometry, materials.PaletteMaterial001, 9]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube029_red_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube031_ark_brown_0.geometry,
          materials.PaletteMaterial001,
          91,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube031_ark_brown_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube031_cheragh_0.geometry,
          materials.PaletteMaterial002,
          91,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube031_cheragh_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.Cube128_ark_brown_0.geometry,
          materials.PaletteMaterial001,
          97,
        ]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube128_ark_brown_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube128_gree_0.geometry, materials.PaletteMaterial001, 33]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube128_gree_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube145_gree_0.geometry, materials.PaletteMaterial001, 64]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube145_gree_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube177_gree_0.geometry, materials.PaletteMaterial001, 16]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube177_gree_0.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cube224_gree_0.geometry, materials.PaletteMaterial001, 5]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube224_gree_0.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/city2-transformed.glb");
