/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 glyptoteket.glb --types --transform --shadows --keepnames --draco . 
Files: glyptoteket.glb [48.13MB] > /Users/Carsten.Hoyer/Workspace/glyptoteket/public/glyptoteket-transformed.glb [3.25MB] (93%)
*/
// @ts-nocheck

import * as THREE from "three";
import React, { useMemo, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Aset_building_trim_S_vcdxfcjdw_04_LOD0002: THREE.Mesh;
    BG: THREE.Mesh;
    BACK001: THREE.Mesh;
    FRONT001: THREE.Mesh;
    Plane014: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane019: THREE.Mesh;
  };
  materials: {
    EMPTY: THREE.MeshStandardMaterial;
    ["EMPTY.BackgroundPlane"]: THREE.MeshStandardMaterial;
    ["test-displacement-1.003"]: THREE.MeshStandardMaterial;
    ["WinterGarden-Floor"]: THREE.MeshStandardMaterial;
    ["Column-green"]: THREE.MeshPhysicalMaterial;
    ["Glass - Dome"]: THREE.MeshPhysicalMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "1 First FloorAction";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/glyptoteket-transformed.glb",
    "."
  ) as GLTFResult;
  const material = useMemo(() => new THREE.MeshBasicMaterial(), []);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="1_First_Floor">
          <mesh
            name="Aset_building_trim_S_vcdxfcjdw_04_LOD0002"
            castShadow
            receiveShadow
            geometry={nodes.Aset_building_trim_S_vcdxfcjdw_04_LOD0002.geometry}
            material={materials.EMPTY}
            position={[0.512, 4.39, 15.563]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.003, 0.003, 0.002]}
          />
        </group>
        <mesh
          name="BG"
          castShadow
          receiveShadow
          geometry={nodes.BG.geometry}
          material={materials["EMPTY.BackgroundPlane"]}
          position={[0, -0.047, 0]}
          scale={801.929}
        />
        <mesh
          name="BACK001"
          castShadow
          receiveShadow
          geometry={nodes.BACK001.geometry}
          material={materials.EMPTY}
          position={[9.659, 4.923, -9.847]}
          scale={[1.048, 0.695, 0.744]}
        />
        <mesh
          name="FRONT001"
          castShadow
          receiveShadow
          geometry={nodes.FRONT001.geometry}
          material={materials["test-displacement-1.003"]}
          position={[0, 2.243, 15.054]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Plane014"
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials["WinterGarden-Floor"]}
          position={[0, 0.005, 4.487]}
        />
        <mesh
          name="Cylinder006"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials["Column-green"]}
          position={[-2.829, 0, 2.264]}
          scale={[0.096, 0.11, 0.096]}
        />
        <mesh
          name="Plane015"
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={nodes.Plane015.material}
          position={[0, 0, -6.184]}
          scale={2.72}
        />
        <mesh
          name="Plane019"
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials["Glass - Dome"]}
          position={[0, 1.487, 15.032]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.742}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/glyptoteket-transformed.glb");
